name: vaxcare_mobile
description: "Application mobile VacxCare pour le suivi vaccinal des enfants."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  google_fonts: ^6.1.0
  http: ^1.2.0
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.3.0
  flutter_localizations:
    sdk: flutter
  socket_io_client: ^2.0.3+1
  table_calendar: ^3.1.2
  flutter_ringtone_player: ^4.0.0
  audioplayers: ^6.1.0
  fl_chart: ^0.69.0
  url_launcher: ^6.3.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
